#!/bin/bash

git checkout master
cp -r src /tmp

git checkout gh-pages
cp -r /tmp/src/* .

git add .
git commit -m 'ADD: Update'

git push origin gh-pages

git checkout master
git clean -df
git submodule update
